### ISSUE TITLE
Doesn't support private registries

### ISSUE THREAD

**Issue by pthrasher** [amaizfinance/redis-operator#10]
The key `imagePullSecrets` must be added to the spec for the containers.

https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod

I needed to alter the redis docker container to not call `chown` -- Ended up having to host it on a public repo.

**Comment by nrvnrvn** [comment]
Thanks for pointing this out! Will be fixed shortly.
