### ISSUE TITLE
Support renaming commands

### ISSUE THREAD

**Issue by logdnalf** [amaizfinance/redis-operator#16]
Renaming commands is not supported and specifically ignored by the Redis Operator: https://github.com/amaizfinance/redis-operator/blob/381d91fe6ec9490de5e7c29b60b5ccc19b94d00a/pkg/controller/redis/object_generator.go#L105

Can we remove this restriction? Renaming commands is quite useful and can improve security.

**Comment by nrvnrvn** [comment]
Hi! I think it is possible. Initially I introduced this restriction to protect some essential configuration options. Excluding the `rename-command` was a way to protect a user from shooting their leg. On the other hand we have two options for removing this restriction:
1) allow `rename-command` as is
2) allow `rename-command` but protect some essential commands like `REPLICAOF`.

The first option is super easy and it will be sole user's responsibility to apply any renamings with caution.
The second option implies introducing some parsing logic and a list of excluded commands but I am not sure if it is worth spending time on it.

**Comment by nrvnrvn** [comment]
superseded by https://github.com/nrvnrvn/redis-operator/issues/3
