### ISSUE TITLE
Example in Readme does not work

### ISSUE THREAD

**Issue by msiebuhr** [amaizfinance/redis-operator#17]
```sh
$ kubectl apply -f example/k8s_v1alpha1_redis_cr.yaml
```

Makes  the redis-operator fail with this error (`kubectl logs -n redis-operator pod/redis-operator-xx-yy`):

    "error":"failed to fetch password: Secret \"redis-password-secret\" not found"

Commenting out the `secret`-section in the example YAML greatly improves things :)

**Comment by msiebuhr** [comment]
Next up, bringing up the first container fails with the following found in the bottom of `kubectl describe pod/redis-example-0`:

    Liveness probe errored: rpc error: code = Unknown desc = failed to exec in container: failed to start exec "ab2e8545ad6aa48e09fb5af94a59c8d19af501c5134cfdba922c800bd2f90896": OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "apparmor failed to apply profile: write /proc/self/attr/exec: operation not permitted": unknown

(I'm running on microk8s with a recent `sudo microk8s.reset` to clean things up.)

**Comment by asumner** [comment]
@nrvnrvn just needs a tweak on documentation to ensure if you leave it enabled, don't forget to create the secret!
