### ISSUE TITLE
Please add support redis cluster.

### ISSUE THREAD

**Issue by asumner** [amaizfinance/redis-operator#20]
@asumner as of now it does not support redis cluster unfortunately.

But I will be happy to add support for it.

This operator's [initial goal](https://github.com/amaizfinance/redis-operator#design-and-goals) was to support `1 master <-> N replicas` architecture in the same way Sentinel provides it but without the burden of maintaining Sentinel itself.

Redis Cluster is `N masters * N replicas` and requires a bit different approach to setting up and managing.

If you need support for sharding and all the rest Cluster features immediately this operator is not for you. :(

If `soon` is a matter of couple of months then I will be happy to help you with it :)

_Originally posted by @nrvnrvn in https://github.com/amaizfinance/redis-operator/issues/18#issuecomment-689987738_

**Comment by nrvnrvn** [comment]
superseded by https://github.com/nrvnrvn/redis-operator/issues/4
