### ISSUE TITLE
Support setting ImagePullPolicy

### ISSUE THREAD

**Issue by johnerikhalse** [amaizfinance/redis-operator#23]
Is there a reason that ImagePullPolicy is hardcoded to 'Always'?

https://github.com/amaizfinance/redis-operator/blob/381d91fe6ec9490de5e7c29b60b5ccc19b94d00a/pkg/controller/redis/object_generator.go#L292
https://github.com/amaizfinance/redis-operator/blob/71e4f9cdc176293779e986c5abea2ffbd7e4059c/pkg/controller/redis/object_generator.go#L366

I would prefer it to be 'IfNotPresent', but best of all let it be configurable. For the last option I guess the CRD must be changed as well.

**Comment by nrvnrvn** [comment]
Hi @johnerikhalse,

I am currently working on the v1 (#12), and the idea is that the Redis CRD will be a thin wrapper around the [StatefulSetSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#statefulsetspec-v1-apps) giving the end user almost full control of the generated StatefulSets, Pods and Containers.
