### ISSUE TITLE
internal/informers error

### ISSUE THREAD

**Issue by asumner** [amaizfinance/redis-operator#26]
Hi @nrvnrvn  the operator seems to get unstable with this error. 
(We upgraded some time ago to K8s AKS version 1.18.8 and the cluster seemed to be working fine then errored, any clues what this process is doing that couldn't reach 10.0.0.1?

1123 23:41:35.966281       1 reflector.go:134] pkg/cache/internal/informers_map.go:196: Failed to list *v1.Pod: Get https://10.0.0.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E1123 23:41:35.968999       1 reflector.go:134] pkg/cache/internal/informers_map.go:126: Failed to list *v1.ConfigMap: Get https://10.0.0.1:443/api/v1/configmaps?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E1123 23:41:36.019562       1 reflector.go:134] pkg/cache/internal/informers_map.go:126: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E1123 23:41:36.020778       1 reflector.go:134] pkg/cache/internal/informers_map.go:126: Failed to list *v1.StatefulSet: Get https://10.0.0.1:443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E1123 23:41:36.021841       1 reflector.go:134] pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.Redis: Get https://10.0.0.1:443/apis/k8s.amaiz.com/v1alpha1/redis?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E1123 23:41:36.023000       1 reflector.go:134] pkg/cache/internal/informers_map.go:126: Failed to list *v1beta1.PodDisruptionBudget: Get https://10.0.0.1:443/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout

**Comment by nrvnrvn** [comment]
This error indicates that the K8s api server is either unresponsive or unreachable for some reason.

Can you reach this URL from inside other containers?
How does the `env` look like in other containers?

This is an example of normal behavior with a reachable API server and for a pod that is not allowed to talk to the API server:

```
❯ k run lol --rm -ti --restart Never --image alpine
If you don't see a command prompt, try pressing enter.
/ # apk add --quiet curl jq && env | grep KUBE
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://10.43.0.1:443
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
KUBERNETES_SERVICE_HOST=10.43.0.1
/ # KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
/ # curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/default/pods/$HOSTNAME | jq
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "pods \"lol\" is forbidden: User \"system:serviceaccount:default:default\" cannot get resource \"pods\" in API group \"\" in the namespace \"default\"",
  "reason": "Forbidden",
  "details": {
    "name": "lol",
    "kind": "pods"
  },
  "code": 403
}
```
