### ISSUE TITLE
Support setting the redis save config option

### ISSUE THREAD

**Issue by stocksr** [amaizfinance/redis-operator#27]
the redis save option in the config file allows multiple lines: e.g. 
```
save 900 1
save 300 10
save 60 10000
```
because this operator uses a key-value map for the config we are only allowed a single save option.

**Comment by nrvnrvn** [comment]
fair enough! Thanks for raising this.

For v1 I am planning to get rid of the KV map in favor of plaintext configs to keep it close to native Redis experience.

**Comment by nrvnrvn** [comment]
superseded by https://github.com/nrvnrvn/redis-operator/issues/5
