### ISSUE TITLE
Master service not available

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [amaizfinance/redis-operator#3]
When I was testing the redis master slave switch, I manually stopped the kubelet of the node where the current redis master is located and found the service unavailable. The endpoints of redis-master does not contain pod information
![image](https://user-images.githubusercontent.com/46734380/57913411-223cb000-78bf-11e9-9b1f-8a68f65fcea7.png)

**Comment by nrvnrvn** [comment]
I haven't tested this scenario but judging by the master Pod hanging in `Terminating 0 23m` state kubernetes is also stuck with the kubelet shut off =)

I am not sure how kubernetes itself should react to situations like this one.

Could you please attach the logs of the operator?

**Comment by wanghe-fit2cloud** [comment]
when I stopped kubelet, the operator did not print any logs.
the operator version is 0.0.2

![image](https://user-images.githubusercontent.com/46734380/57920621-0bea2080-78ce-11e9-95b9-998107b589b4.png)

**Comment by nrvnrvn** [comment]
While this is an interesting issue it looks like the main problem is the Pod stuck in `Terminating` state. I am not sure what kind of events kube-apiserver posts in the situation when one of the nodes' kubelet is stopped.

Redis-operator watches the events regarding `Statefulsets` it owns. If it is alive then it has received no events about StatefulSet changes and thus no reconfiguration has been done. That's the only reason why the master service still points to the stuck `Pod`.

Unfortunately I have no means to try to reproduce the issue. If you could send some logs or `kubectl get events` of what's going on during the time when you stop kubelet I would highly appreciate.
