### ISSUE TITLE
How to manage multiple _loadmodule_

### ISSUE THREAD

**Issue by step76** [amaizfinance/redis-operator#34]
As stated in the title I need to add in the config of Redis **two** _loadmodule_ directives.\
If I compile the yaml with a section like this
```yaml
config:
  loadmodule: "first module"
  loadmodule: "second module"
```
only the second module will be loaded and the first one is discarded because in YAML only the first occurrence is retained.

I thought about generating a custom config file in a _init container_  and the include it, but the _include_ keyword is forbidden.

Do you think I can try some workaround?

Can I contribute to the operator with a patch to address this issue? How could be changed the config management in a way to support this kind of configuration? I was thinking to add a specific _module_ section, what do you think about?

**Comment by nrvnrvn** [comment]
superseded by https://github.com/nrvnrvn/redis-operator/issues/7
