### ISSUE TITLE
Redis password problem

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [amaizfinance/redis-operator#4]
When I set the secret of password, the auth command can be executed correctly, but it can still be logged in without password.

![image](https://user-images.githubusercontent.com/46734380/57914055-814ef480-78c0-11e9-9884-443276146cda.png)

**Comment by nrvnrvn** [comment]
This behavior is expected.
Password is stored in the `REDISCLI_AUTH` environment variable and does not require to pass it through the command-line arg.

Ref: https://github.com/antirez/redis/pull/5460

**Comment by pms1969** [comment]
Is there a way to not have a password?

**Comment by nrvnrvn** [comment]
@pms1969 Setting password is optional. If your clients require unauthenticated access then you simply shouldn't set it up.
