### ISSUE TITLE
no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by stocksr** [amaizfinance/redis-operator#42]
Hi it looks like CustomResourceDefinitions   v1beata1 has been removed since kubernetes version 1.22

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122

This is a problem for us as docker desktop updated Kubernetes to version 1.22.4  in version 4.3.0 (released 2021-12-02)

**Comment by stocksr** [comment]
Happy to attempt a PR if you want

**Comment by nrvnrvn** [comment]
superseded by https://github.com/nrvnrvn/redis-operator/issues/8
