### ISSUE TITLE
Update APIs to work with Kubernetes 1.22+ and create helm chart for installing the operator

### ISSUE THREAD

**Issue by lord-kyron** [amaizfinance/redis-operator#46]
I've tried to deploy this operator, but I stumbled upon not fixed API support for kubernetes 1.22+
Also it will be very good if there was a helm chart to install the operator with!
Thanks!

**Comment by shamil** [comment]
I think this repo is no longer tracked, @nrvnrvn moved the development under his account.
I guess this will be resolved in v1. For reference, [here](https://github.com/nrvnrvn/redis-operator/issues/1) is a link to the roadmap.

**Comment by nrvnrvn** [comment]
Superseded by https://github.com/nrvnrvn/redis-operator/issues/11
