### ISSUE TITLE
Operator unable to find secret defined in secret ref

### ISSUE THREAD

**Issue by ZeroDeltaAlpha** [amaizfinance/redis-operator#47]
## Issue

Deploying the example and creating a Redis object works great and creates a redis deployment, but uncommenting the secretref causes the CRD to never finish creating the Redis statefulset and the operator pod has has the following log messages:

<code>
{"level":"error","ts":"2022-07-03T14:25:57.927Z","logger":"controller-runtime.controller","msg":"Reconciler error","controller":"redis-controller","request":"redis-operator/staging","error":"failed to fetch password: Secret \"\" not found","stacktrace":"github.com/amaizfinance/redis-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tvendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/amaizfinance/redis-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258\ngithub.com/amaizfinance/redis-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\ngithub.com/amaizfinance/redis-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\ngithub.com/amaizfinance/redis-operator/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\ngithub.com/amaizfinance/redis-operator/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\ngithub.com/amaizfinance/redis-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/amaizfinance/redis-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}</code>

---

We have tried deploying the secret to both the destination namespace and the operator namespace, both fail to find it.Also manually editing the Redis CRD Object to modify the secretref field causes it to be set to {} after saving the kubectl edit.

I've also tried setting `  json: x-kubernetes-preserve-unknown-fields: true` on the CRD source itself to see if kubernetes was pruning the field but observed no change in the CRD.

Kubernetes Version:
Client Version: v1.22.4
Server Version: v1.22.7+k3s1

**Comment by nrvnrvn** [comment]
it is probably related to the kubernetes version. Also, bear in mind that this operator is no longer actively maintained and all development has been moved to https://github.com/nrvnrvn/redis-operator/

**Comment by ZeroDeltaAlpha** [comment]
Thanks @nrvnrvn, I'll follow along there.
