### ISSUE TITLE
can use redis 2.8 ?

### ISSUE THREAD

**Issue by kingsqv** [amaizfinance/redis-operator#7]
can use redis 2.8 version

**Comment by nrvnrvn** [comment]
Hi! 

Minimum supported version is `5.0`.

Out of curiousity, what is the rationale behind using redis 2.8?

**Comment by kingsqv** [comment]
In my env  the app is useing redis 2.8
Does support pv？

**Comment by nrvnrvn** [comment]
If by pv you mean persistent volume then yes, it is possible. I will add an example of it soon. You can find an example here https://github.com/amaizfinance/redis-operator/issues/6

**Comment by kingsqv** [comment]
thanks
